version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=demo-secret-key-change-in-production
      - ENCRYPTION_KEY=32-character-key-for-demo-testing
      - DB_TYPE=sqlite
      - GIN_MODE=release
    volumes:
      - ./pharmacy.db:/app/pharmacy.db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend