# TrueNAS SCALE Docker Compose - Fast Deployment
# File: truenas-docker-compose-fast.yaml
# Format: Docker Compose v3.8 (NOT Kubernetes)

version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: aetherpharma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  aetherpharma:
    image: golang:1.21-alpine
    container_name: aetherpharma-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "80:8080"
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: pharmacy_user
      DB_PASSWORD: pharmacy_password
      DB_NAME: pharmacy_db
      JWT_SECRET: demo
      ENCRYPTION_KEY: 32-character-encryption-key-here
    working_dir: /app
    command: |
      sh -c "
        echo 'Testing connection...' &&
        apk add --no-cache git &&
        git clone --depth 1 https://github.com/jhustcoding/AetherPharma.git . &&
        touch .env &&
        sleep 5 &&
        go run cmd/server/main.go
      "
    volumes:
      - app_data:/data

volumes:
  postgres_data:
  app_data: