version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: aetherpharma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: golang:1.21-alpine
    container_name: aetherpharma-backend
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: pharmacy_user
      DB_PASSWORD: pharmacy_password
      DB_NAME: pharmacy_db
      DB_SSL_MODE: disable
      JWT_SECRET: truenas-demo-secret
      ENCRYPTION_KEY: 32-character-encryption-key-here
      GIN_MODE: release
    volumes:
      - backend_code:/app
    command: >
      sh -c "
      apk add --no-cache git curl &&
      if [ ! -f /app/go.mod ]; then
        git clone --depth 1 https://github.com/jhustcoding/AetherPharma.git /tmp/repo &&
        cp -r /tmp/repo/* /app/ &&
        rm -rf /tmp/repo
      fi &&
      cd /app &&
      sleep 10 &&
      go run cmd/server/main.go
      "

  frontend:
    image: node:18-alpine
    container_name: aetherpharma-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://192.168.0.9:8080
      DISABLE_ESLINT_PLUGIN: "true"
      TSC_COMPILE_ON_ERROR: "true"
      GENERATE_SOURCEMAP: "false"
      CI: "false"
      SKIP_PREFLIGHT_CHECK: "true"
    volumes:
      - frontend_code:/app
    command: >
      sh -c "
      apk add --no-cache git &&
      if [ ! -f /app/package.json ]; then
        git clone --depth 1 https://github.com/jhustcoding/AetherPharma.git /tmp/repo &&
        cp -r /tmp/repo/frontend/* /app/ &&
        rm -rf /tmp/repo
      fi &&
      cd /app &&
      npm install &&
      npm start
      "

volumes:
  postgres_data:
  backend_code:
  frontend_code: