# TrueNAS SCALE Docker Compose - Test Without Git
# File: truenas-docker-compose-test.yaml
# Format: Docker Compose v3.8 (NOT Kubernetes)

version: "3.8"

services:
  test-app:
    image: golang:1.21-alpine
    container_name: test-app
    ports:
      - "8080:8080"
    command: |
      sh -c "
        echo 'Creating simple test server...' &&
        cat > server.go << 'EOF'
        package main
        import (
            \"fmt\"
            \"net/http\"
        )
        func main() {
            http.HandleFunc(\"/\", func(w http.ResponseWriter, r *http.Request) {
                fmt.Fprintf(w, \"AetherPharma Test Server Running!\")
            })
            fmt.Println(\"Server starting on :8080\")
            http.ListenAndServe(\":8080\", nil)
        }
        EOF
        go run server.go
      "